title: Nick Carroll, MSBA # your name (or website title) here
logo: "https://github.com/nbcarroll/nbcarroll.github.io/raw/master/images/Headshot.png"


description: > # your text below (remove <br> elements if you don't need line breaks)
  ðŸ“§ <a href="mailto:nickbcarroll@gmail.com">Email</a> | <a href="https://www.linkedin.com/in/nick-carroll1/">LinkedIn</a>

  <br><br>
  
  <b>MS Business Analytics</b><br>
  <i>Seattle University</i>
  <br><br>
  <b>Additional Certifications</b> <br>

  âž¤ Advanced Applied SQL for Business Intelligence and Analytics | Udemy <br>
   âž¤ Tableau 2022 Advanced: Master Tableau in Data Science | Udemy
  <br>
  âž¤ Power Query, Power Pivot | Maven Analytics
  <br>
  âž¤ Google Analytics | Google <br>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
